export const artcats = [
  "Abstract Art",
  "Landscape Painting",
  "Portrait Art",
  "Still Life",
  "Surrealism",
  "Cubism",
  "Impressionism",
  "Pop Art",
  "Minimalism",
  "Realism",
  "Contemporary Art",
  "Street Art",
  "Expressionism",
  "Digital Art",
  "Sculpture",
  "Conceptual Art",
  "Art Photography",
  "Installation Art",
  "Folk Art",
  "Outsider Art",
];

